---
# Docker User
dockerUser: geoffh1977
dockerUserEmail: geoffh1977@gmail.com
license: gnu-gpl-v3.0

# Source Build Variables
buildImageName: pandoc
buildImageVersion: latest

# Final Image Variables
finalImageName: pandoc-pdf
finalImageVersion: latest
appName: Pandoc PDF
