# Pandoc With Latex PDF Extensions
FROM {{ dockerUser + "/" + buildImageName + ":" + buildImageVersion }}
LABEL maintainer="{{ dockerUser }} <{{ dockerUserEmail }}>"
USER root

# Latex For PDF
# hadolint ignore=DL3018,DL3019
RUN apk add -U --repository http://dl-3.alpinelinux.org/alpine/v3.9/main poppler harfbuzz-icu && \
    apk add -U --repository http://dl-3.alpinelinux.org/alpine/v3.9/community zziplib texlive-full && \
    ln -s /usr/bin/mktexlsr /usr/bin/mktexlsr.pl

USER ${ALPINE_USER}
